### ISSUE TITLE
Blabot.net down?

### ISSUE THREAD

**Issue by LeBaux** [blabot/blabot-core-php#1]
Hi, I was about to generate some quality ipsum, and the website is gone. But this repo seems to be active. What is next for blábot? Thank you.

**Comment by tomaskuba** [comment]
Yea sorry blabot.net domain is lost (not my fault). So I'm trying to made Blábot it up and running with new code and simple form at blabot.cz as soon as possible.

**Comment by LeBaux** [comment]
Blabot.cz is way better TLD anyway :) Thank you for getting back to me and your effort to bring blábot back!

**Comment by tomaskuba** [comment]
Hi Blabot is up’n’running at https://www.blabot.cz again. More features and dictionaries are comming soon. Happy Blaboting 🤖

**Comment by LeBaux** [comment]
I absolutely love the new version. TBF I do not even miss the ability to specify the number of paragraphs and what not. Thank you for taking good care of Blábot!
